/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.solid.UI;

import co.unicauca.domain.DegreeWorkStatus;
import co.unicauca.domain.FormatA;
import co.unicauca.solid.domain.services.CoordinateerService;
import javax.swing.JOptionPane;

/**
 *
 * @author jusev
 */
public class EvaluationFormatA extends javax.swing.JFrame {

    /**
     * Creates new form EvaluationFormatA
     */
    public EvaluationFormatA() {
        initComponents();
        loadFormats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblMenu = new javax.swing.JLabel();
        cbFormats = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rbApprove = new javax.swing.JRadioButton();
        rbDecline = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservations = new javax.swing.JTextArea();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setFont(new java.awt.Font("Lucida Console", 0, 27)); // NOI18N
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("EVALUATE FORMAT A");

        cbFormats.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbFormats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormatsActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECT FORMAT A");

        rbApprove.setText("APPROVE");
        rbApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbApproveActionPerformed(evt);
            }
        });

        rbDecline.setText("DECLINE");
        rbDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDeclineActionPerformed(evt);
            }
        });

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel2.setText("OBSERVATIONS:");

        txtObservations.setColumns(20);
        txtObservations.setRows(5);
        jScrollPane1.setViewportView(txtObservations);

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(rbApprove))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(cbFormats, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(rbDecline)))))
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblMenu)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFormats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbApprove)
                    .addComponent(rbDecline))
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(volver))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFormatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFormatsActionPerformed

    private void rbApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbApproveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbApproveActionPerformed

    private void rbDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDeclineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDeclineActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        FormatA formato = (FormatA) cbFormats.getSelectedItem();
        if (formato == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Formato A.");
            return;
        }

        DegreeWorkStatus decision;
        if (rbApprove.isSelected()) {
            decision = DegreeWorkStatus.APROBADO;
        } else if (rbDecline.isSelected()) {
            decision = DegreeWorkStatus.RECHAZADO;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar Aprobar o Rechazar.");
            return;
        }

        String obs = txtObservations.getText();

        CoordinateerService service = new CoordinateerService();
        service.evaluateFormatA(formato.getId(), decision, obs);

        JOptionPane.showMessageDialog(this,
                "Evaluación guardada y notificación enviada.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);

        // 🔹 Preparar para otra evaluación
        cbFormats.setSelectedIndex(-1);
        rbApprove.setSelected(false);
        rbDecline.setSelected(false);
        txtObservations.setText("");

    }//GEN-LAST:event_saveActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Controller.OpenPanel(new Menu());
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvaluationFormatA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvaluationFormatA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvaluationFormatA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvaluationFormatA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EvaluationFormatA().setVisible(true);
        });
    }

    private void loadFormats() {
        try {
            var repo = co.unicauca.solid.domain.access.Factory
                    .getInstance()
                    .getFormatARepository("default");

            java.util.List<FormatA> formatos = repo.getAll();

            javax.swing.DefaultComboBoxModel<FormatA> model = new javax.swing.DefaultComboBoxModel<>();
            for (FormatA f : formatos) {
                model.addElement(f);
            }

            cbFormats.setModel(model);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error cargando formatos: " + ex.getMessage(),
                    "ERROR",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<FormatA> cbFormats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JRadioButton rbApprove;
    private javax.swing.JRadioButton rbDecline;
    private javax.swing.JButton save;
    private javax.swing.JTextArea txtObservations;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
