/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.solid.UI;

import co.unicauca.domain.DegreeWorkStatus;
import co.unicauca.domain.FormatA;
import co.unicauca.solid.domain.services.CoordinateerService;
import javax.swing.JOptionPane;

/**
 *
 * @author jusev
 */
public class EvaluateFormatA extends javax.swing.JPanel {

    /**
     * Creates new form EvaluateFormatA
     */
    public EvaluateFormatA() {
        initComponents();
        decisionGroup = new javax.swing.ButtonGroup();
    decisionGroup.add(rbApprove);
    decisionGroup.add(rbDecline);
        loadFormats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbFormats = new javax.swing.JComboBox<>();
        rbApprove = new javax.swing.JRadioButton();
        rbDecline = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservations = new javax.swing.JTextArea();
        save = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        jLabel1.setText("SELECT FORMAT A");

        lblMenu.setFont(new java.awt.Font("Lucida Console", 0, 27)); // NOI18N
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("EVALUATE FORMAT A");

        jLabel2.setText("SELECT FORMAT A");

        cbFormats.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbFormats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormatsActionPerformed(evt);
            }
        });

        rbApprove.setText("APPROVE");
        rbApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbApproveActionPerformed(evt);
            }
        });

        rbDecline.setText("DECLINE");
        rbDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDeclineActionPerformed(evt);
            }
        });

        jLabel3.setText("OBSERVATIONS:");

        txtObservations.setColumns(20);
        txtObservations.setRows(5);
        jScrollPane1.setViewportView(txtObservations);

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbApprove)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbDecline))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbFormats, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(volver)
                .addGap(147, 147, 147)
                .addComponent(save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblMenu)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbFormats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbApprove)
                    .addComponent(rbDecline))
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(volver))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbFormatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFormatsActionPerformed

    private void rbApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbApproveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbApproveActionPerformed

    private void rbDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDeclineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDeclineActionPerformed


    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        FormatA formato = (FormatA) cbFormats.getSelectedItem();
        if (formato == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Formato A.");
            return;
        }

        DegreeWorkStatus decision;
        if (rbApprove.isSelected()) {
            decision = DegreeWorkStatus.APROBADO;
        } else if (rbDecline.isSelected()) {
            decision = DegreeWorkStatus.RECHAZADO;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar Aprobar o Rechazar.");
            return;
        }

        String obs = txtObservations.getText();

        CoordinateerService service = new CoordinateerService();
        service.evaluateFormatA(formato.getId(), decision, obs);

        JOptionPane.showMessageDialog(this,
                "Evaluación guardada y notificación enviada.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);

        // 🔹 Preparar para otra evaluación
        cbFormats.setSelectedIndex(-1);
        rbApprove.setSelected(false);
        rbDecline.setSelected(false);
        txtObservations.setText("");
        if (cbFormats.getItemCount() > 0) {
        cbFormats.setSelectedIndex(0);
}

    }//GEN-LAST:event_saveActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Controller.OpenPanel(new Menu());
    }//GEN-LAST:event_volverActionPerformed
    private void loadFormats() {
        try {
            var repo = co.unicauca.solid.domain.access.Factory
                    .getInstance()
                    .getFormatARepository("default");

            java.util.List<FormatA> formatos = repo.getAll();

            javax.swing.DefaultComboBoxModel<FormatA> model = new javax.swing.DefaultComboBoxModel<>();
            for (FormatA f : formatos) {
                model.addElement(f);
            }

            cbFormats.setModel(model);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error cargando formatos: " + ex.getMessage(),
                    "ERROR",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<FormatA> cbFormats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JRadioButton rbApprove;
    private javax.swing.JRadioButton rbDecline;
    private javax.swing.JButton save;
    private javax.swing.JTextArea txtObservations;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
    private javax.swing.ButtonGroup decisionGroup;
}
