/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.solid.UI;

/**
 *
 * @author jusev
 */
public class MenuCoordinateer extends javax.swing.JPanel {

    /**
     * Creates new form MenuTeacher
     */
    public MenuCoordinateer() {
        initComponents();
    }
    private EvaluateFormatA evalFormatAPanel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        pnlOptions = new javax.swing.JPanel();
        btnBackToHome = new javax.swing.JButton();
        btnEvaluateFormatA1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        lblMenu.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");

        pnlOptions.setLayout(new java.awt.GridLayout(3, 1, 0, 12));

        btnBackToHome.setText("Home");
        btnBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeActionPerformed(evt);
            }
        });
        pnlOptions.add(btnBackToHome);

        btnEvaluateFormatA1.setText("Evaluar Formato");
        btnEvaluateFormatA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluateFormatA1ActionPerformed(evt);
            }
        });
        pnlOptions.add(btnEvaluateFormatA1);

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlOptions.add(btnExit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblMenu)
                .addGap(52, 52, 52)
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed
        Controller.OpenPanel(new Selector());
    }//GEN-LAST:event_btnBackToHomeActionPerformed

    private void btnEvaluateFormatA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluateFormatA1ActionPerformed
        if (evalFormatAPanel == null) {
            evalFormatAPanel = new EvaluateFormatA();
        }
        Controller.OpenPanel(evalFormatAPanel);
    }//GEN-LAST:event_btnEvaluateFormatA1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JButton btnEvaluateFormatA1;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JPanel pnlOptions;
    // End of variables declaration//GEN-END:variables
}
