/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.solid.UI;
//imports
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import co.unicauca.domain.Register;
import java.util.Arrays;
import javax.swing.JOptionPane;
/**
 *@summary Patron formato encargado de la recolección y verificación de datos
 * @param nombre, apellido, celular, programa, email, rol, contraseña
 * @author JUANDA
 */
public class RegisterForm extends javax.swing.JPanel{

    /**
     * Creates new form Registry
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblNúmero = new javax.swing.JLabel();
        inApellidos = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        inNumTel = new javax.swing.JTextField();
        lblPrograma = new javax.swing.JLabel();
        inPrograma = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        inEmail = new javax.swing.JTextField();
        lblContra = new javax.swing.JLabel();
        lblContra2 = new javax.swing.JLabel();
        inContra = new javax.swing.JPasswordField();
        inContra2 = new javax.swing.JPasswordField();
        lblTitulo = new javax.swing.JLabel();
        btReg = new javax.swing.JButton();
        lblRol = new javax.swing.JLabel();
        inRol = new javax.swing.JComboBox<>();

        inNombre.setName("Nombre"); // NOI18N

        lblNombre.setLabelFor(inNombre);
        lblNombre.setText("Nombre:");

        lblNúmero.setLabelFor(inNumTel);
        lblNúmero.setText("Numero de celular:");

        lblApellidos.setLabelFor(inApellidos);
        lblApellidos.setText("Apellidos:");

        lblPrograma.setLabelFor(inPrograma);
        lblPrograma.setText("Programa:");

        inPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria de Sistemas", "Ingenieria Electronica y Telecomunicaciones", "Automatica Industrial", "Tecnologia en Telematica" }));

        lblEmail.setLabelFor(inEmail);
        lblEmail.setText("Email:");

        lblContra.setLabelFor(inContra);
        lblContra.setText("Contraseña:");

        lblContra2.setLabelFor(inContra2);
        lblContra2.setText("Comfirmar contraseña:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro");

        btReg.setText("Registrar");
        btReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegActionPerformed(evt);
            }
        });

        lblRol.setText("Rol:");

        inRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNúmero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inNumTel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inApellidos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrograma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inPrograma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inRol, 0, 362, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inContra2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btReg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContra2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inContra)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(inNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNúmero)
                    .addComponent(inNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrograma)
                    .addComponent(inPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(inEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRol)
                    .addComponent(inRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContra)
                    .addComponent(inContra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContra2)
                    .addComponent(inContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btReg))
        );

        inNombre.getAccessibleContext().setAccessibleName("Nombre");
        inNombre.getAccessibleContext().setAccessibleDescription("Nombre del usuario");
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Se encarga de hacer el registro cuando se presiona el boton de registro
     * @param evt 
     */
    private void btRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegActionPerformed
        //Obtiene los datos del formulario
        String nom = inNombre.getText().trim();
        String ape = inApellidos.getText().trim();
        Long numCel = Long.parseLong(inNumTel.getText().trim());//Opcional
        String programa = inPrograma.getSelectedItem().toString();
        String email = inEmail.getText().trim();
        String rol = inRol.getSelectedItem().toString();
        char[] contra = inContra.getPassword();
        char[] contra2 = inContra2.getPassword();//Confirma la contraseña
        //Se manda la info al controlador para que haga el registro
        Controller.registrar(nom, ape, email, rol, programa, numCel, contra, contra2);
    }//GEN-LAST:event_btRegActionPerformed
    
    //<editor-fold defaultstate="collapsed" desc="Declaracion de variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReg;
    private javax.swing.JTextField inApellidos;
    private javax.swing.JPasswordField inContra;
    private javax.swing.JPasswordField inContra2;
    private javax.swing.JTextField inEmail;
    private javax.swing.JTextField inNombre;
    private javax.swing.JTextField inNumTel;
    private javax.swing.JComboBox<String> inPrograma;
    private javax.swing.JComboBox<String> inRol;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblContra2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNúmero;
    private javax.swing.JLabel lblPrograma;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
