package co.unicauca.solid.UI;
//imports
import co.unicauca.domain.Program;
import co.unicauca.domain.Roles;
/**
 *@summary Patron formato encargado de la recolección y verificación de datos
 * @param nombre, apellido, celular, programa, email, rol, contraseña
 * @author JUANDA
 */
public class RegisterForm extends javax.swing.JPanel{

    /**
     * Creates new form Registry
     */
    public RegisterForm() {
        initComponents();
        loadProgramas();
        loadRoles();
        
    }
    
    private void loadProgramas() {
        var listProgram = Controller.getAllProgram();
        inPrograma.removeAllItems(); 
        for (Program p : listProgram) {
            inPrograma.addItem(p); 
        }
    }
    
    private void loadRoles() {
        var listRoles = Controller.getAllRoles();
        inRol.removeAllItems(); 
        for (var r : listRoles) {
            inRol.addItem(r); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlAll = new javax.swing.JPanel();
        pnlPersonalInfo = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        inNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        inApellidos = new javax.swing.JTextField();
        lblNúmero = new javax.swing.JLabel();
        inNumTel = new javax.swing.JTextField();
        lblPrograma = new javax.swing.JLabel();
        inPrograma = new javax.swing.JComboBox<>();
        lblRol = new javax.swing.JLabel();
        inRol = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        inEmail = new javax.swing.JTextField();
        lblContra = new javax.swing.JLabel();
        inContra = new javax.swing.JPasswordField();
        lblContra2 = new javax.swing.JLabel();
        inContra2 = new javax.swing.JPasswordField();
        pnlSaveAndHome = new javax.swing.JPanel();
        btReg = new javax.swing.JButton();
        btnBackToHome = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 500));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro");

        pnlPersonalInfo.setLayout(new java.awt.GridLayout(8, 2, 0, 2));

        lblNombre.setLabelFor(inNombre);
        lblNombre.setText("Nombre:");
        pnlPersonalInfo.add(lblNombre);

        inNombre.setText("Dayana");
        inNombre.setName("Nombre"); // NOI18N
        pnlPersonalInfo.add(inNombre);
        inNombre.getAccessibleContext().setAccessibleName("Nombre");
        inNombre.getAccessibleContext().setAccessibleDescription("Nombre del usuario");

        lblApellidos.setLabelFor(inApellidos);
        lblApellidos.setText("Apellidos:");
        pnlPersonalInfo.add(lblApellidos);

        inApellidos.setText("Idrobo");
        pnlPersonalInfo.add(inApellidos);

        lblNúmero.setLabelFor(inNumTel);
        lblNúmero.setText("Numero de celular:");
        pnlPersonalInfo.add(lblNúmero);

        inNumTel.setText("3007463520");
        inNumTel.setToolTipText("");
        pnlPersonalInfo.add(inNumTel);

        lblPrograma.setLabelFor(inPrograma);
        lblPrograma.setText("Programa:");
        pnlPersonalInfo.add(lblPrograma);
        pnlPersonalInfo.add(inPrograma);

        lblRol.setText("Rol:");
        pnlPersonalInfo.add(lblRol);
        pnlPersonalInfo.add(inRol);

        lblEmail.setLabelFor(inEmail);
        lblEmail.setText("Email:");
        pnlPersonalInfo.add(lblEmail);

        inEmail.setText("dayana@unicauca.edu.co");
        pnlPersonalInfo.add(inEmail);

        lblContra.setLabelFor(inContra);
        lblContra.setText("Contraseña:");
        pnlPersonalInfo.add(lblContra);

        inContra.setText("Dayana$123");
        pnlPersonalInfo.add(inContra);

        lblContra2.setLabelFor(inContra2);
        lblContra2.setText("Confirmar contraseña:");
        pnlPersonalInfo.add(lblContra2);

        inContra2.setText("Dayana$123");
        pnlPersonalInfo.add(inContra2);

        pnlSaveAndHome.setLayout(new java.awt.GridLayout(2, 1, 0, 2));

        btReg.setText("Guardar");
        btReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegActionPerformed(evt);
            }
        });
        pnlSaveAndHome.add(btReg);

        btnBackToHome.setText("Home");
        btnBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeActionPerformed(evt);
            }
        });
        pnlSaveAndHome.add(btnBackToHome);

        javax.swing.GroupLayout pnlAllLayout = new javax.swing.GroupLayout(pnlAll);
        pnlAll.setLayout(pnlAllLayout);
        pnlAllLayout.setHorizontalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSaveAndHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllLayout.createSequentialGroup()
                        .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        pnlAllLayout.setVerticalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(pnlSaveAndHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Se encarga de hacer el registro cuando se presiona el boton de registro
     * @param evt 
     */
    private void btRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegActionPerformed
        //Obtiene los datos del formulario
        String nom = inNombre.getText().trim();
        String ape = inApellidos.getText().trim();
        Long numCel = Long.parseLong(inNumTel.getText().trim());//Opcional
        //String programa = inPrograma.getSelectedItem().toString();
        var programa = (Program) inPrograma.getSelectedItem();
        String email = inEmail.getText().trim();
        var rol = (Roles) inRol.getSelectedItem();
        char[] contra = inContra.getPassword();
        char[] contra2 = inContra2.getPassword();//Confirma la contraseña
        //Se manda la info al controlador para que haga el registro
        Controller.registrar(nom, ape, email, rol, programa, numCel, contra, contra2);
    }//GEN-LAST:event_btRegActionPerformed

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed
        Controller.OpenPanel(new Selector());
    }//GEN-LAST:event_btnBackToHomeActionPerformed
    
    //<editor-fold defaultstate="collapsed" desc="Declaracion de variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReg;
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JTextField inApellidos;
    private javax.swing.JPasswordField inContra;
    private javax.swing.JPasswordField inContra2;
    private javax.swing.JTextField inEmail;
    private javax.swing.JTextField inNombre;
    private javax.swing.JTextField inNumTel;
    private javax.swing.JComboBox<Program> inPrograma;
    private javax.swing.JComboBox<Roles> inRol;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblContra2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNúmero;
    private javax.swing.JLabel lblPrograma;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlPersonalInfo;
    private javax.swing.JPanel pnlSaveAndHome;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
